### ISSUE TITLE
Build onnx2trt error

### ISSUE THREAD

**Issue by 1LOVESTaylor** [onnx/onnx-tensorrt#18]
When I attempt to make onnx2trt, I meet the error as below:
[100%] Built target onnx_proto
[100%] Built target nvonnxparser_plugin
[100%] Built target nvonnxparser_static
[100%] Built target nvonnxparser
[100%] Built target nvonnxparser_runtime
[100%] Built target nvonnxparser_runtime_static
[100%] Linking CXX executable onnx2trt
libnvonnxparser_static.a(builtin_op_importers.cpp.o): In function `onnx2trt::(anonymous namespace)::importConcat(onnx2trt::IImporterContext*, onnx2trt_onnx::NodeProto const&, std::vector<onnx2trt::TensorOrWeights, std::allocator<onnx2trt::TensorOrWeights> >&)':
builtin_op_importers.cpp:(.text+0x1a259): undefined reference to `nvinfer1::plugin::createConcatPlugin(int, bool)'
collect2: error: ld returned 1 exit status
CMakeFiles/onnx2trt.dir/build.make:105: recipe for target 'onnx2trt' failed
make[2]: *** [onnx2trt] Error 1
CMakeFiles/Makefile2:256: recipe for target 'CMakeFiles/onnx2trt.dir/all' failed
make[1]: *** [CMakeFiles/onnx2trt.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

I've installed tensorrt4.0. However, it seems like the definition of `nvinfer1::plugin::createConcatPlugin(int, bool)' cannot be found, which is declared in NvInferPlugin.h. Can anyone help?

**Comment by paghdv** [comment]
hey @1LOVESTaylor , did you find the problem/solution?

**Comment by haohaibo** [comment]
Hi @1LOVESTaylor , it works fine with TensorRT5.0. So you can re-build onnx-tensorrt with TensorRT5.0 .

**Comment by kevinch-nv** [comment]
Please refer to the master branch for updated instructions for building with later TensorRT versions. If you are still having problems, feel free to reopen this issue or file a new one.
