### PR TITLE
    Fix build on Ubuntu 20.04

### PR DESCRIPTION
**Pull request by deadeyegoodwin**
Remove std::move in return to resolve this build failure:

    [ 66%] Building CXX object CMakeFiles/onnxruntime_providers.dir/workspace/onnxruntime/onnxruntime/core/providers/cpu/activation/activations.cc.o
    /workspace/onnxruntime/cmake/external/onnx-tensorrt/builtin_op_importers.cpp: In function ‘std::vector<nvinfer1::PluginField> onnx2trt::{anonymous}::loadFields(string_map<std::vector<unsigned char> >&, const OnnxAttrs&, const nvinfer1::PluginFieldCollection*)’:
    /workspace/onnxruntime/cmake/external/onnx-tensorrt/builtin_op_importers.cpp:3737:21: error: moving a local object in a return statement prevents copy elision [-Werror=pessimizing-move]
     3737 |     return std::move(fields);
          |            ~~~~~~~~~^~~~~~~~
    /workspace/onnxruntime/cmake/external/onnx-tensorrt/builtin_op_importers.cpp:3737:21: note: remove ‘std::move’ call

### CODE REVIEW

**Review by kevinch-nv — APPROVED** [review]

**Comment by kevinch-nv** [comment]
@deadeyegoodwin can you sign off this commit and we can then merge

**Comment by deadeyegoodwin** [comment]
@kevinch-nv  signed
